INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AurelianT', '4420aur', 'Aurelian', 'Temisan', '0744896214', 'a.temisan@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AlexandruR', 'med123', 'Alexandru', 'Rafila', '0768521478', 'rafirafi@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('VasilcoiuI', 'pas000', 'Ili Marian', 'Vasilcoiu', '0743159753', 'iliemarian@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('VasileP', 'parola321', 'Vasile', 'Prodan', '0748891114', 'v.prodan@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('BogdanS', '5544bog', 'Bogdan', 'Serban', '0765369742', 'bogdanserb@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('MarianS', 'parola135', 'Marian', 'Stoica', '0754895256', 'stoicamarian@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('PaulD', 'parola987', 'Paul', 'Dondoe', '0743996214', 'd.paul@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('ConstantinM', 'parola357', 'Constantin', 'Mogosanu', '0755685492', 'mogos.ctin@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('CosminV', 'pas557', 'Cosmin', 'Vlad', '0769621478', 'cosminv@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('IonT', 'ambani123', 'Ion Ion', 'Tiriac', '0744589321', 'ionion@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('DanielaM', 'parola753', 'Daniela', 'Marcu', '0749895514', 'm.daniela@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AlexandruM', 'parola963', 'Alexandra', 'Marinescu', '0766001202', 'marinescu.alexandra@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('CristinaU', 'parola9876', 'Cristina Teodora', 'Uncheasu', '0768961002', 'cris.uncheasu@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('MonicaT', 'parola1415',  'Monica Daniela', 'Tunaru', '0763012021', 'tunaru.dani@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AuraC', 'parola1213', 'Aura', 'Calota', '0766895147', 'a.calota@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AlexandruN', 'parola9101', 'Alexandru', 'Naicu', '0766850007', 'rosu.alex@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('MonicaB', 'monmon', 'Monica', 'Barladeanu', '0765789456', 'moni.moni@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('DanielN', 'pas415', 'Daniel', 'Naicu', '0744558812', 'naicu.daniel@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AdrianN', 'glontul123', 'Adrian', 'Nastase', '0744001122', 'cris.maria@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('CrinaP', 'pas6615', 'Crina', 'Popa', '0785274102', 'popa.cristina@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('MarianG', 'militia123', 'Marian', 'Godina', '0773578108', 'zamfir.bogdan@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('GabrielV', 'parola1617', 'Gabriela Alexandra', 'Vasilcoiu', '0743397158', 'gabi.vasilcoiu@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('GhitaM', 'minge123', 'Ghita', 'Muresan', '0744920783', 'maria.ispas@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('IonM', 'parola1819', 'Ion Marin', 'Ciubotariu', '0755248963', 'ciubotariu.marin@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('RobertS', '55rob', 'Robert', 'Sperila', '0743258147', 'sperila.robert@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('MadalinT', 'pas322', 'Madalin', 'Toma', '0758951357', 'toma.madalin@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('AurelianC', 'pas1009', 'Aurelian Ionut', 'Cristoiu', '0744998855', 'cristoiu.aurelian@yahoo.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('ClaraS', 'fclar123', 'Clara Maria', 'Serban', '0754892301', 'serban.clara@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('TatianaF', 'pas55990', 'Tatiana Floriana', 'Belulescu', '0756849210', 'tatiana.floriana@gmail.com');
INSERT INTO users (username, password, first_name,last_name, phone_number, email_address) VALUES ('VioricaV', 'pas55990', 'Viorica', 'Vasilescu', '0744852145', 'vio.vasilescu@gmail.com');
