INSERT INTO hotels (hotel_name, hotel_location, rating, breakfast, wifi_connection, private_parking, minibar)
VALUES
    ('Hotel Transilvania', 'Cluj-Napoca', 4, true, true, true, true),
	('Hotel Athenee Palace Hilton', 'Bucuresti', 5, true, true, true, true),
	('Hotel Grand  Continental', 'Bucuresti', 4, true, true, false, true),
	('Hotel Bella Muzica', 'Brasov', 3, false, true, false, true),
	('Hotel Articus', 'Craiova', 3, true, false, false, true),
	('Hotel Ramada Parc', 'Bucuresti', 4, true, false, false, true),
	('Hotel Ibis', 'Cluj-Napoca', 3, true, false, false, true),
	('Hotel Kronwell', 'Brasov', 5, true, true, false, false),
	('Hotel Mercure', 'Sibiu', 4, true, false, false, true),
	('Hotel JW Marriott', 'Bucuresti', 5, true, false, false, true),
	('Hotel Continental Forum', 'Sibiu', 4, true, false, false, true),
	('Hotel Radisson Blu', 'Bucuresti', 5, true, true, false, true),
	('Hotel City Plaza', 'Cluj-Napoca', 3, true, true, false, true),
	('Hotel Golden Tulip', 'Bucuresti', 4, true, true, false, true),
	('Hotel Hilton', 'Sibiu', 5, true, true, true, true),
	('Hotel Green House', 'Craiova', 3, true, false, false, true),
	('Hotel Crowne Plaza', 'Bucuresti', 4, true, false, false, true),
	('Hotel Aro Palace', 'Brasov', 3, true, false, false, false),
    ('Hotel Novotel', 'Bucuresti', 4, true, true, false, true),
    ('Hotel Golden Tulip Ana Tower', 'Sibiu', 4, true, true, true, false),
    ('Hotel Premier', 'Sibiu', 3, true, false, false, true),
    ('Hotel Sheraton', 'Bucuresti', 5, true, true, false, true),
    ('Hotel Europeca', 'Craiova', 4, true, false, false, true),
    ('Hotel Capitol', 'Timisoara', 4, true, true, false, true),
    ('Hotel InterContinental', 'Bucuresti', 5, true, true, true, true),
    ('Hotel Opera Plaza', 'Cluj-Napoca', 3, true, false, false, true),
    ('Hotel RIN Central', 'Bucuresti', 4, true, false, false, true),
    ('Hotel Ramada', 'Sibiu', 4, true, false, false, true),
    ('Hotel Hilton Garden Inn', 'Bucharest', 5, true, true, true, true),
    ('Hotel Ramada', 'Craiova', 4, true, true, false, true);
